# Stage 1: Build Stage
FROM python:3.9 AS builder

WORKDIR /app

RUN apt update

COPY requirements.txt .

RUN pip install -r requirements.txt

# -------------------------------------

FROM python:3.9-slim

WORKDIR /app

RUN apt update

COPY --from=builder /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/

COPY . .

ENTRYPOINT [ "python", "run.py" ]

